import Breadcrumb from '@components/Breadcrumb'
import Sidebar from '@components/Sidebar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body>
        <div className='flex p-10'>
          <Sidebar />

          <div>
            <Breadcrumb />

            {children}
          </div>
        </div>
      </body>
    </html>
  )
}

export default RootLayout
